import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Providers from './providers';

import '@Styles/global/index.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => (
  <html lang="en">
    <body className={inter.className}>
      <Providers>
        {children}
      </Providers>
    </body>
  </html>
);

export default RootLayout;
